Added User model
TimurShakhlai/trainee-planner pull request #13
Opened 2023-08-22 12:17 UTC by TimurShakhlai

## Task:
Add model User

## Change proposed in this pull request:

1. Added User model
2. Added tests to User model

2023-08-25 12:45 UTC, DariaAres commented on db/seeds.rb
Сделай, пожалуйста сиды только на девелопмент окружении и Дима советует не отделять скопы на разные файлы по моделькам потому что потом могут возникнуть проблемы с ассоциациями

2023-08-25 12:45 UTC, DariaAres commented on db/seeds/development.rb
> +    email: Faker::Internet.email,
seed на email принято представлять в формате user_#{i}@example.com

2023-08-25 12:45 UTC, DariaAres commented on spec/factories/users.rb
> +    last_name { Faker::Name.last_name }
У тебя  фамилия - необязательное поле: Дима советует на такие поля делать trait-ы

2023-08-25 12:45 UTC, DariaAres commented on spec/factories/users.rb
> +    email { Faker::Internet.email }
Тут нужно добавить что email уникальный

2023-08-25 12:45 UTC, DariaAres commented on config/routes.rb
> +  devise_for :users
Наверно роуты в меньшей степени относятся к моделям, нежели контроллеры и вью, поэтому они не нужны в этом pr

2023-08-25 16:08 UTC, DariaAres submitted a review, later dismissed

2023-08-28 09:21 UTC, TsikhanauDzmitry requested changes

2023-08-28 09:21 UTC, TsikhanauDzmitry commented on app/models/user.rb
> +  validates :first_name, presence: true
Я бы советовал разделить пустой строчкой

2023-08-28 09:21 UTC, TsikhanauDzmitry commented on app/models/user.rb
> +  validates :first_name, presence: true
Что думаешь, это все необходимые валидации?

2023-08-28 09:21 UTC, TsikhanauDzmitry commented on db/migrate/20230825020732_devise_create_users.rb
> +      t.string :first_name
Это же необходимое поле. Думаю добавить проверку на уровне БД. Как считаешь?

2023-08-28 09:21 UTC, TsikhanauDzmitry commented on db/migrate/20230825021606_add_indexes_to_users.rb
> +    add_index :users, :reset_password_token, unique: true
Почему это в отдельном PR?

2023-08-28 09:21 UTC, TsikhanauDzmitry commented on db/seeds.rb
> +load(Rails.root.join('db', 'seeds', "#{Rails.env.downcase}.rb")) if Rails.env.development?
Очень не люблю, когда после больших комментариев сразу идет код без пустых строк в начале

2023-08-28 09:21 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +  User.create_or_find_by!(
По какому полю ищется пользователь? Если запустить Сиды еще раз, то они запустится без ошибок?

2023-08-28 09:21 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +    trait :last_name do
Я бы рекомендовал делать трейды с более точными именами. В нашем случае было бы славно сделать что-то типа: `with_last_name`

2023-08-28 15:12 UTC, TimurShakhlai commented on app/models/user.rb
> +  validates :first_name, presence: true
можно наверное добавить обязательность эмейла и пароля, уникальность почты
добавил

2023-08-28 15:13 UTC, TimurShakhlai commented on db/migrate/20230825020732_devise_create_users.rb
> +      t.string :first_name
исправил

2023-08-28 15:14 UTC, TimurShakhlai commented on db/migrate/20230825021606_add_indexes_to_users.rb
> +    add_index :users, :reset_password_token, unique: true
рубокоп ругается на длину метода

2023-09-01 06:00 UTC, TimurShakhlai commented on db/seeds/development.rb
> +  User.create_or_find_by!(
ищется по емейл, при повторном могут крашнуться
исправил

2023-09-01 06:01 UTC, TimurShakhlai commented on spec/factories/users.rb
> +    trait :last_name do
исправил

2023-09-01 06:33 UTC, DariaAres commented on db/seeds/development.rb
> +end
Пожешь, пожалуйста,  переписать создание юзера так, чтобы при повторном запуске сидов ничего не сломалось

2023-09-01 06:33 UTC, DariaAres commented on spec/models/user_spec.rb
> +    end
У тебя есть еще вилидация на длину пароля. Напиши на нее тест, пожалуйста

2023-09-01 06:36 UTC, TimurShakhlai commented on db/seeds/development.rb
> +end
так оно и так не ломается

2023-09-01 06:37 UTC, TimurShakhlai commented on spec/models/user_spec.rb
> +    end
справедливо, исправил

2023-09-01 07:07 UTC, DariaAres approved these changes, later dismissed

2023-09-01 11:51 UTC, TsikhanauDzmitry requested changes

2023-09-01 11:51 UTC, TsikhanauDzmitry commented on app/models/user.rb
> +  validates :password, presence: true, length: { minimum: 8 }
Странное решение. Обычно длина пароля с верхней границы не часто ограничивается, а если и ограничивается, то 20ью символами например. Есть ли смысл в данной валидации?

2023-09-01 11:51 UTC, TsikhanauDzmitry commented on db/migrate/20230825021606_add_indexes_to_users.rb
> +    add_index :users, :reset_password_token, unique: true
Я бы тогда рассматривал другие пути решения данной проблемы:

1. Отменил бы эту проверку для миграций у самого рубокопа
2. Если и отделять миграции, то не логично разъеденять добавление индексов и полей, к которым они добавляются. Может лучше имена и фамилии перенести в другую миграцию?

2023-09-01 11:51 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +end
Это выглядит очень не очень... Рекомендую почитать документацию: https://api.rubyonrails.org/classes/ActiveRecord/Relation.html

2023-09-01 11:51 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +  subject(:user) { build :user }
Рекомендую параметры в методе указывать в скобочках

2023-09-01 11:51 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +      )
Что это? В методичке такого не было... @DariaAres тебе это понравилось?

2023-09-01 11:54 UTC, TimurShakhlai commented on app/models/user.rb
> +  validates :password, presence: true, length: { minimum: 8 }
а почему верхняя граница, если я указываю минимальное значение?

2023-09-01 14:01 UTC, TimurShakhlai commented on db/seeds/development.rb
> +end
исправил

2023-09-01 14:02 UTC, TimurShakhlai commented on spec/models/user_spec.rb
> +  subject(:user) { build :user }
исправил

2023-09-01 14:07 UTC, TimurShakhlai commented on spec/models/user_spec.rb
> +      )
исправил

2023-09-02 05:23 UTC, DariaAres approved these changes, later dismissed

2023-09-02 05:28 UTC, DariaAres commented on spec/models/user_spec.rb
> +    it { expect(user).to validate_presence_of :password }
:first_name, :email, :password в скобочках

2023-09-04 09:19 UTC, TimurShakhlai commented on spec/models/user_spec.rb
> +    it { expect(user).to validate_presence_of :password }
исправил

2023-09-04 11:10 UTC, DariaAres submitted a review, later dismissed

2023-09-05 06:27 UTC, TsikhanauDzmitry requested changes

2023-09-05 06:27 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +    password { Faker::Internet.password }
У тебя стоит минимум 8 символов в пароле. Уверен, что все пароли факера будут удовлетворять данной валидации?

2023-09-05 09:35 UTC, TimurShakhlai commented on spec/factories/users.rb
> +    password { Faker::Internet.password }
исправил

2023-09-05 09:44 UTC, dasha-sync approved these changes

2023-09-05 10:03 UTC, TsikhanauDzmitry approved these changes

2023-09-07 01:43 UTC, merged