Added ci/cd
TimurShakhlai/trainee-planner pull request #9
Opened 2023-08-08 07:26 UTC by TimurShakhlai

## Task:
Add ci/cd

## Change proposed in this pull request:

* Added .github/workflows directory
* Added ci/cd.yml
* Configured style code check with rubocop and test coverage check

2023-08-08 07:55 UTC, trufanovnik approved these changes

2023-08-08 10:50 UTC, TsikhanauDzmitry requested changes
Почему на данном PR я не вижу никаких проверок? Вы должны добавить CI/CD на каждый push коммита, в любом PR. Т.е. после добавленных изменений в PR должны ранаться (от слова run) проверки

2023-08-14 13:34 UTC, trufanovnik submitted a review, later dismissed

2023-08-18 07:25 UTC, TsikhanauDzmitry submitted a review, later dismissed

2023-08-20 12:13 UTC, merged